---
title: "Learning Reflection"
subtitle: "Week 5"
format: html
editor: visual
---

# Learning reflections

Learning reflections are part of your weekly homework and have a weight of 20% of your final grade. Write a reflection in your own words on the different parts of the weeks material below. You can also use your learning reflections as a notebook as you work through exercises or readings. Write as much as you like, but a minimum of 100 words in total.

# Lecture

\<This lecture deepened my understanding of tidy data principles and the importance of data structure in analysis. I appreciated the practical examples, especially the issues encountered when working with inconsistent data types and how to resolve them. The emphasis on converting between wide and long formats was particularly enlightening, as it showed how tidy data facilitates clearer visualizations and more efficient analysis. I now better understand how respecting data types and choosing the right structure enhances reproducibility and collaboration. The live coding exercises made the concepts accessible and directly applicable to real world data.\>

# Homework Assignment

<!--# Add your reflections on the homework programming assignment here -->

# Readings

\<**“Tidy Data” chapter from R for Data Science:** The chapter on tidy data reframed my understanding of data structuring in R by showing that nearly any dataset can and should be reshaped into a consistent format. By enforcing three clear rules: that each variable resides in its own column, each observation in its own row, and each cell contains a single value, the messy becomes manageable . Learning tools like pivot_longer() and pivot_wider() in tidyr was eye‑opening, as they demonstrate how to reshape tables without altering underlying values. Most importantly, once data is tidy, working with the tidyverse becomes fluid, saving time and reducing errors. I now appreciate how tidying is essential groundwork for clear, efficient analysis.\>

# Submit learning reflections

## Stage, Commit & Push to GitHub

This final section introduces the workflow you need to follow at the end of each live coding exercise, homework assignment, learning reflection. It ensures that all the changes you have made to files in this repository (folder) are synced with the version that is stored on GitHub. The steps will be described at the end of each of the files.

1.  Open the Git pane in RStudio. It's in the top right corner in a separate tab.
2.  **Stage** your changes by checking appropriate box next to all files (if you select one file with your mouse, you can then highlight them all with Ctrl + A on your keyboard and check all boxes)
3.  Write a meaningful commit message (e.g. "Completed homework assignment 1b) in the **Commit message** box
4.  Click **Commit**. Note that every commit needs to have a commit message associated with it.
5.  Go to your course-material GitHub repo and refresh the page. You should see your commit message next to the updated files.

## Open an issue on GitHub

Once you have ensured that the Quarto document renders without errors and you have pushed all your changes to GitHub, it is to complete the assignment by opening an issue on your course-material GitHub repo.

1.  Navigate to your course-material GitHub repo.
2.  Click on **Issues**, and then **New issue** button.
3.  Write a meaningful title in the **Title** field
4.  Tag the course instructor with using the `@` sign in combination with `larnsce` as the username
5.  Add any questions or comments
